### ISSUE TITLE
Can only standard chess pgn format moves be supported?

### ISSUE THREAD

**Issue by cjssh1002** [nguyenpham/oobs#4]
Can only standard chess pgn format moves be supported?

For example, can you support Asian traditional chess pgn like janggi?

**Comment by nguyenpham** [comment]
In theory, the standard can support almost all chess variants since it could store positions and moves as text (EPDs and moves in coordination). The code of the chessboard has a base class (BoardCore) that is designed for chess variants. We have tested that class for extending ones for Chess960, Xiangqi, Jeiqi, XChess... all could work well.

Thus the answer is: both the standard and code could support those chess variants. However, I don't know about them! I hope someone knows, is willing to support, and jumps in to help.
